model:
  gaussian:
    class_path: internal.models.appearance_gs2d.AppearanceGS2D
    init_args:
      sh_degree: 0
      appearance_feature_dims: 64
      optimization:
        appearance_feature_lr_init: 2e-3
  renderer:
    class_path: internal.renderers.appearance_2dgs_renderer.Appearance2DGSRenderer
    init_args:
      model:
        is_view_dependent: false
        normalize: true
      optimization:
        warm_up: 1000
  metric: internal.metrics.gs2d_metrics.GS2DMetrics
  density:
    class_path: internal.density_controllers.gs2d_density_controller.GS2DDensityController
    init_args:
      cull_opacity_threshold: 0.05
data:
  val_max_num_images_to_cache: -1
  test_max_num_images_to_cache: -1
  parser:
    class_path: Colmap
    init_args:
      split_mode: "reconstruction"
