model:
  renderer:
    class_path: internal.renderers.taming_3dgs_renderer.Taming3DGSRenderer
    init_args:
      anti_aliased: true
  metric:
    class_path: internal.metrics.vanilla_with_fused_ssim_metrics.VanillaWithFusedSSIMMetrics
