trainer:
  strategy:
    class_path: internal.mp_strategy.MPStrategy
  devices: -1
model:
  renderer: 
    class_path: internal.renderers.gsplat_distributed_renderer.GSplatDistributedRenderer
    init_args:
      tile_based_culling: true
  density: internal.density_controllers.distributed_vanilla_density_controller.DistributedVanillaDensityController
  metric:
    fused_ssim: true