# more acceleration, but slightly lower quality
model:
  gaussian:
    init_args:
      optimization:
        optimizer: SelectiveAdam
  renderer: 
    class_path: internal.renderers.gsplat_v1_renderer.GSplatV1Renderer
    init_args:
      separate_sh: true
      tile_based_culling: true
  metric:
    init_args:
      fused_ssim: true