model:
  gaussian:
    init_args:
      optimization:
        optimizer: SelectiveAdam
  renderer:
    class_path: internal.renderers.gsplat_v1_renderer.GSplatV1Renderer
    init_args:
      tile_based_culling: true
